spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=public
    username: f1app
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

