version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
        - '5432:5432'
    networks:
        - f1-network

networks:
 f1-network:
  name: 'f1-network'
